### ISSUE TITLE
Cannot read properties of undefined (reading 'release')

### ISSUE THREAD

**Issue by unchaptered** [Broccoli-Velog/Broccoli-Backend#4]
## 행동

```cmd
Server is running on 3000
TypeError: Cannot read properties of undefined (reading 'release')
    at file:///D:/Broccoli/Broccoli-Backend/src/database/index.js:18:14
    at D:\Broccoli\Broccoli-Backend\node_modules\mysql2\lib\pool.js:60:18
    at PoolConnection.<anonymous> (D:\Broccoli\Broccoli-Backend\node_modules\mysql2\lib\connection.js:775:13)        
    at Object.onceWrapper (node:events:642:26)
    at PoolConnection.emit (node:events:539:35)
    at PoolConnection._notifyError (D:\Broccoli\Broccoli-Backend\node_modules\mysql2\lib\connection.js:236:12)       
    at PoolConnection._handleFatalError (D:\Broccoli\Broccoli-Backend\node_modules\mysql2\lib\connection.js:167:10)  
    at PoolConnection._handleNetworkError (D:\Broccoli\Broccoli-Backend\node_modules\mysql2\lib\connection.js:180:10)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
```

### 1. 작업 환경

```cmd
- Node : v16.15.1
- npm : v8.11.0
```

**Comment by unchaptered** [comment]
### 문제 원인

mysql2 와 mysql 이 둘 다 깔려있어서 에러가 발생했습니다.

### 해결 방법

환경 변수 파일 안에 오기입 된 `IPv4` 을 수정하고 `./src/db.js` 를 삭제하고 `./src/index.js` 에 연결된 부분을 제거했습니다.
